from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse
from sqlalchemy.orm import Session
from typing import List
from html import escape

from app.database import get_db
from app.services.incident_service import get_recent_incidents, get_incident_details, update_incident_status, assign_incident

router = APIRouter(prefix="/api/v1/incidents")

@router.get("/")
def list_incidents(limit: int = 50, db: Session = Depends(get_db)):
    incidents = get_recent_incidents(db, limit=limit)
    return incidents

@router.get("/{incident_id}")
def get_incident(incident_id: str, db: Session = Depends(get_db)):
    details = get_incident_details(db, incident_id)
    if not details:
        raise HTTPException(status_code=404, detail="Incident not found")
    return details

@router.put("/{incident_id}/status")
def update_status(incident_id: str, status: str, user: str = "System", db: Session = Depends(get_db)):
    updated = update_incident_status(db, incident_id, status, user)
    if not updated:
        raise HTTPException(status_code=404, detail="Incident not found")
    return updated

@router.get("/{incident_id}/report")
def download_report(incident_id: str, db: Session = Depends(get_db)):
    details = get_incident_details(db, incident_id)
    if not details:
        raise HTTPException(status_code=404, detail="Incident not found")
    inc = details["incident"]
    timeline = details["timeline"] or []
    timeline_html = "".join(
        f"<li><span class='ts'>[{escape(str(t.created_at))}]</span> {escape(t.event_description or '')}</li>"
        for t in timeline
    ) or "<li>No events.</li>"
    html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>Incident Report — {escape(inc.id)}</title>
<style>body{{font-family:Arial,sans-serif;margin:40px;background:#f7f9fc;color:#222}}
h1,h2{{color:#1f4e79}}.card{{background:#fff;padding:20px;margin-bottom:20px;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,.08)}}
.label{{font-weight:bold}}.sev{{display:inline-block;padding:3px 10px;border-radius:4px;color:#fff;font-weight:bold;background:#b22222}}
ul{{padding-left:20px}}.ts{{color:#888;font-size:.85em}}.brand{{color:#888;font-size:.8em;margin-top:30px;text-align:center}}</style></head>
<body><h1>Incident Report</h1>
<div class="card"><h2>Overview</h2>
<p><span class="label">Incident ID:</span> {escape(inc.id)}</p>
<p><span class="label">Title:</span> {escape(inc.title or '')}</p>
<p><span class="label">Severity:</span> <span class="sev">{escape(inc.severity or '')}</span></p>
<p><span class="label">Status:</span> {escape(inc.status or '')}</p>
<p><span class="label">Created:</span> {escape(str(inc.created_at))}</p>
<p><span class="label">Updated:</span> {escape(str(inc.updated_at))}</p>
<p><span class="label">Description:</span><br>{escape(inc.description or 'No description.')}</p></div>
<div class="card"><h2>Activity Timeline</h2><ul>{timeline_html}</ul></div>
<div class="brand">Generated by Smart SIEM Risk Engine</div></body></html>"""
    return HTMLResponse(
        content=html,
        headers={"Content-Disposition": f'attachment; filename="incident_{inc.id}.html"'},
    )


@router.put("/{incident_id}/assign")
def assign(incident_id: str, user_id: int, user_name: str, db: Session = Depends(get_db)):
    updated = assign_incident(db, incident_id, user_id, user_name)
    if not updated:
        raise HTTPException(status_code=404, detail="Incident not found")
    return updated
