LOW_RISK_MAX = 29
MEDIUM_RISK_MAX = 59
HIGH_RISK_MAX = 79
CRITICAL_RISK_MAX = 100

ACTION_STORE_ONLY = "store_only"
ACTION_ALERT_ONLY = "alert_only"
ACTION_GENERATE_REPORT = "generate_report"
ACTION_BLOCK_AND_REPORT = "block_and_report"